refactor interactions with multiplayer slots
osuAkatsuki/bancho-service pull request #3
Opened 2022-07-13 05:33 UTC by cmyui

2022-07-13 05:38 UTC, cmyui commented on objects/match.py
> +            if self.slots[slotID].team == matchTeams.RED:
this fixes AKAT-184

2022-07-13 05:42 UTC, infernalfire72 approved these changes, later dismissed

2022-07-13 06:34 UTC, cmyui commented on objects/match.py
> +            self.remove_referee(self.hostUserID)
this fixes [AKAT-185](https://osuakatsuki.atlassian.net/browse/AKAT-185) - Passing host off while being staff will remove referee status

2022-07-18 17:11 UTC, tsunyoku requested changes

2022-07-18 17:11 UTC, tsunyoku commented on objects/match.py
> +        return exc_value is not None
this is buggy behaviour from testing, wouldn't recommend

2022-07-18 17:11 UTC, tsunyoku commented on objects/match.py
> +                 traceback: Optional[TracebackType]) -> bool:
```suggestion
                 traceback: Optional[TracebackType]) -> None:
```

2022-07-18 17:12 UTC, tsunyoku commented on objects/match.py
> +        return exc_value is not None
```suggestion
```

2022-07-18 17:13 UTC, tsunyoku approved these changes

2022-07-18 17:13 UTC, merged